/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: gavinchan180 (https://sketchfab.com/gavinchan180)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/gumball-darwin-82b5e27bed644635b2e5b8c218074e20
title: Gumball & Darwin
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const Model = (props) => {
  const { nodes, materials } = useGLTF("/gumball__darwin.glb");
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[0.06, 0.03, -0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_4.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.23]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.74, 1.17, 0.74]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_6.geometry}
              material={materials.Metallic_0}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.23]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.74, 1.17, 0.74]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_8.geometry}
              material={materials.Metallic_1}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_10.geometry}
              material={materials.Metallic_2}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_12.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_14.geometry}
              material={materials.Metallic_3}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_16.geometry}
              material={materials.Metallic_4}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.15]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_18.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.06, 0.03, -0.14]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.74}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_20.geometry}
              material={materials.Metallic_2}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_22.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_24.geometry}
              material={materials.Metallic_5}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_26.geometry}
              material={materials.Metallic_6}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_28.geometry}
              material={materials.Metallic_7}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_30.geometry}
              material={materials.Metallic_5}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_32.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_34.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_36.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_38.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_40.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_42.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_44.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_46.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_48.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_50.geometry}
              material={materials.Metallic_7}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_52.geometry}
              material={materials.Metallic_5}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_54.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_56.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials.Metallic_6}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_60.geometry}
              material={materials.Metallic_7}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_62.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.18]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.21}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_64.geometry}
              material={materials.Metallic_10}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_66.geometry}
              material={materials.Metallic_6}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_68.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_70.geometry}
              material={materials.Metallic_11}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_72.geometry}
              material={materials.Metallic_11}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.3]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.33, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_74.geometry}
              material={materials.Metallic_8}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_76.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_78.geometry}
              material={materials.Metallic_12}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_80.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_82.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_84.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.14, -0.03, -0.33]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={[0.21, 0.43, 0.21]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_86.geometry}
              material={materials.Metallic_12}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.21]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_88.geometry}
              material={materials.Metallic_2}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.21]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_90.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_92.geometry}
              material={materials.Metallic}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_94.geometry}
              material={materials.Metallic_2}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_96.geometry}
              material={materials.Metallic_2}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.21]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_98.geometry}
              material={materials.Metallic_9}
            />
          </group>
          <group
            position={[0.05, 0.02, -0.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={0.82}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_100.geometry}
              material={materials.Metallic}
            />
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/gumball__darwin.glb");

export default Model;
